### ISSUE TITLE
Add a basic README for the project.

### ISSUE THREAD

**Issue by isaactorresmichel** [CrayonEstudioCreativo/raite#1]
The firt step for the project is to add a basic Readme. This readme must describe the intentionallity for the project, basic goals and a presentation of the team working on it.

**Comment by gabitha** [comment]
Cree un PR que añade el REAMDE.md para el proyecto.

**Comment by isaactorresmichel** [comment]
Es un poco básico pero suficiente para comenzar el taller. Gracias @gabitha
